# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Munich Agency
email: irene3molina@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Munich Agency es una agencia de publicidad situada en Málaga (España)
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.munichagency.com/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: munichagency
facebook_username: munichagency
github_username: nadalsol
address_link: https://goo.gl/maps/1tMN7qASPXF2
address_1: C/ Lancelot, 22 - 29738
address_2: Torrre de Benagalbón, Málaga.
address_location: ubicación
phone_country_code: 34
phone: 627 81 50 41
lang: es
google_analytics: UA-131310822-1

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
sass:
  style: compressed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Translations
# common
contact:
  heading: "Contáctanos"
  name: "Nombre"
  phone: "Teléfono"
  email: "E-mail"
  message: "Hola!"
  subject: "Consulta web"
  privacy_text_1: "Acepto la"
  privacy_text_2: "política de privacidad"
  submit: "Enviar"
cookie_message:
  text: "Munich Agency utiliza cookies para esegurar una mejor experiencia en su web. Por favor, lee nuestra"
  text_link: "política de cookies"
footer_legal:
  privacy: "Privacidad"
  cookies: "Cookies"
header:
  home_link: ""
# patterns
404:
  text_1: "Página no encontrada :("
  text_2: "No hemos encontrado la página solicitada."
approach:
  heading: "Filosofía"
customers:
  heading: "Clientes"
nav_main:
  link_1: "quienes-somos"
  text_1: "Quiénes somos"
  link_2: "servicios"
  text_2: "Servicios"
  link_3: "proyectos"
  text_3: "Proyectos"
  link_4: "contacto"
  text_4: "Contacto"
other_projects:
  heading: "Otros proyectos"
projects:
  heading: "Proyectos"

# Collections
collections:
  about_callouts:
    output: true
    permalink: /:collection/:path/
  about_mains:
    output: true
    permalink: /:collection/:path/
  home_approaches:
    output: true
    permalink: /:collection/:path/
  home_carousels:
    output: true
    permalink: /:collection/:path/
  home_customers:
    output: true
    permalink: /:collection/:path/
  home_carousel_projects:
    output: true
    permalink: /:collection/:path/
  home_visions:
    output: true
    permalink: /:collection/:path/
  legal_cookies:
    output: true
    permalink: /:collection/:path/
  legal_privacies:
    output: true
    permalink: /:collection/:path/
  projects:
    output: true
    permalink: /:collection/:path/
  services:
    output: true
    permalink: /:collection/:path/
  the_projects:
    output: true
    permalink: /:collection/:path/
