# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Munich Agency
email: nadalsoler@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Munich Agency es un estudio de publicidad y comunicación situado en Málaga (España)
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.munichagency.com/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: munichagency
facebook_username: munichagency
github_username: nadalsol
address_link: https://goo.gl/maps/1tMN7qASPXF2
address: C/ Lancelot, 22 - 29738 - Torrre de Benagalbón, Málaga.
phone_country_code: 34
phone: 123 456 789
lang: es

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
sass:
  style: compressed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Translations
# common
contact:
  heading: "Contáctanos"
  name: "Nombre"
  phone: "Teléfono"
  email: "E-mail"
  message: "Hola!"
  subject: "Consulta web"
  privacy_text_1: "Acepto la"
  privacy_text_2: "política de privacidad"
  submit: "Enviar"
cookie_message:
  text: "Munich Agency utiliza cookies para esegurar una mejor experiencia en su web. Por favor, lee nuestra"
  text_link: "política de cookies"
footer_legal:
  privacy: "Privacidad"
  cookies: "Cookies"
  terms: "Aviso legal"
header:
  home_link: ""
modal_cookie:
  heading: "Cookies"
  text: "Sus datos formarán parte de un fichero titularidad de Munich Agency y serán tratados para poderle informar periódicamente de novedades, productos y servicios. Puede ejercitar sus derechos de acceso, rectificación, cancelación y oposición, así como revocar su consentimiento para el envío de comunicaciones comerciales electrónicas, enviando un e-mail a nadalsoler@gmail.com. Mediante la inclusión de su correo electrónico y/o teléfono móvil Ud. nos autoriza a enviarle información comercial a través de su cuenta de correo electrónico así como otros medios electrónicos equivalentes."
modal_privacy:
  heading: "Privacidad"
  text: "De conformidad con lo dispuesto en el Reglamento General de Protección de Datos, UE 2016/679, le informamos que sus datos personales son tratados y almacenados por Munich Agency, como responsable del tratamiento, con domicilio social en C/Còrsega 329, 7-B 08037 Barcelona, con la finalidad del mantenimiento de la relación necesaria con usted y de gestionar comunicaciones promocionales e informativas por correo electrónico acerca de Munich Agency, así como sus actividades y eventos que puedan resultar de su interés. Sus datos serán conservados para futuras comunicaciones y almacenaremos sus datos el tiempo necesario para realizar dicha gestión, hasta que solicite su supresión. Usted podrá ejercitar sus derechos de acceso, rectificación, oposición, supresión, limitación y portabilidad, así como su derecho a revocar el consentimiento otorgado por la presente en cualquier momento, mediante comunicación escrita, acompañada de copia de DNI, dirigida a la dirección citada anteriormente o a través del envío de un correo electrónico con firma digital reconocida a la siguiente dirección <a href=\"mailto:nadalsoler@gmail.com\">nadalsoler@gmail.com</a>. Dicha comunicación deberá incluir nombre y apellidos, petición en que se concreta la solicitud, dirección a efectos de notificaciones, fecha, firma y fotocopia del DNI u otro documento válido que lo identifique. Usted tiene derecho, además, a presentar una reclamación ante la autoridad de control competente."
modal_terms:
  heading: "Aviso legal"
  text: "..."
# patterns
404:
  text_1: "Página no encontrada :("
  text_2: "No hemos encontrado la página solicitada."
approach:
  heading: "Filosofía"
customers:
  heading: "Clientes"
nav_main:
  link_1: "quienes-somos"
  text_1: "Quiénes somos"
  link_2: "servicios"
  text_2: "Servicios"
  link_3: "proyectos"
  text_3: "Proyectos"
  link_4: "contacto"
  text_4: "Contacto"
projects:
  heading: "Proyectos"

# Collections
collections:
  about_callouts:
    output: true
    permalink: /:collection/:path/
  about_mains:
    output: true
    permalink: /:collection/:path/
  home_approaches:
    output: true
    permalink: /:collection/:path/
  home_carousels:
    output: true
    permalink: /:collection/:path/
  home_customers:
    output: true
    permalink: /:collection/:path/
  home_visions:
    output: true
    permalink: /:collection/:path/
  projects:
    output: true
    permalink: /:collection/:path/
  services:
    output: true
    permalink: /:collection/:path/
  the_projects:
    output: true
    permalink: /:collection/:path/
